pipeline {
    agent any

    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
        terraform "terraform"
    }

    options {
        skipStagesAfterUnstable()
    }

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = 'project-ecr-repo'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/neellokhandwala/DevOps-CloudOps-automated-project.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('infra') {
                    withAWS(credentials: 'aws creds', region: "${AWS_REGION}") {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra') {
                    withAWS(credentials: 'aws creds', region: "${AWS_REGION}") {
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra') {
                    withAWS(credentials: 'aws creds', region: "${AWS_REGION}") {
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Get AWS Account ID') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws creds') {
                    script {
                        env.AWS_ACCOUNT_ID = sh(
                            script: "aws sts get-caller-identity --query Account --output text",
                            returnStdout: true
                        ).trim()

                        env.ECR_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                        env.IMAGE = "${ECR_URI}/${ECR_REPO}:${IMAGE_TAG}"

                        echo "Using image: ${env.IMAGE}"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE} ./app"
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws creds') {
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | \
                        docker login --username AWS --password-stdin ${ECR_URI}

                        docker push ${IMAGE}

                        docker tag ${IMAGE} ${ECR_URI}/${ECR_REPO}:latest
                        docker push ${ECR_URI}/${ECR_REPO}:latest
                    """
                }
            }
        }

        stage('Clean Local Docker Images') {
            steps {
                sh "docker rmi ${IMAGE} || true"
            }
        }

        stage('ECS Deployment') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws creds') {
                    sh """
                        aws ecs update-service \
                        --cluster project-ecs-cluster \
                        --service project-ecs-service \
                        --force-new-deployment \
                        --region ${AWS_REGION}
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment Successful!'
        }
        failure {
            echo '❌ Deployment Failed! Check logs carefully.'
        }
    }
}
